### ISSUE TITLE
Get Profile Implement

### ISSUE THREAD

**Issue by kkminseok** [kkminseok/real-world-springboot#16]
## Todo

> Implement

- [x] Controller
- [x] Service
- [x] Repostiory

## Todo

> Test

- [x] Controller unit test
- [x] Service unit test
- [x] Service unit test Throw Exception `Not Found User`
- [x] Repository unit test

## Trouble Shooting
> description
```text
Get Profile
GET /api/profiles/:username

Authentication optional, returns a [Profile]
```

**Comment by kkminseok** [comment]
complete
