### ISSUE TITLE
**Favorites Article** API Implement.

### ISSUE THREAD

**Issue by kkminseok** [kkminseok/real-world-springboot#26]
## Todo

> Implement

- [x] Controller
- [x] Service
- [x] Repository

## Todo

> Test

- [x] Controller
- [x] Service
- [x] Repository

-----

- [x] Two user create (user1, user2) -> user2 Create Article -> user1 call Article by user2 Created -> **favorited : false and favorite count : 0**
- [x] Two user create (user1, user2) -> user2 Create Article  -> user1 Favorited Article user2 Created -> user1 call Article by user2 Created -> **favorited : true and favorite count : 1**
- [x] Two user create (user1, user2) -> user2 Create Article  -> user1 Favorited Article user2 Created -> user1 call Article by user2 Created -> **favorited : true and favorite count : 1** -> user1 Favortied Article user2 Created repeat -> **ERROR already favorited article**
- more user create Test
- 

## Trouble Shooting
> description

<img width="1002" alt="image" src="https://user-images.githubusercontent.com/30401054/198868387-2a9305f2-c043-46d7-805b-b6239c17f655.png">
