### ISSUE TITLE
[FE] Register Logic

### ISSUE THREAD

**Issue by kkminseok** [kkminseok/real-world-springboot#36]
## Todo

> Implement

- [x] Register Page Logic Implement
- [x] Email Validation
- [x] Username Validation
- [x] 200 OK -> Profile

## Todo

> Test

- [x] Duplicate User Test - username
- [x] Duplicate User Test - email

## Trouble Shooting
> description

![image](https://user-images.githubusercontent.com/30401054/201801794-7496dfcb-c4c8-4bed-b47a-f7333d07a9cf.png)
