### ISSUE TITLE
[FE] Setting Page Implement

### ISSUE THREAD

**Issue by kkminseok** [kkminseok/real-world-springboot#39]
## Todo

> Implement

- [x] /setting Page Implement

## Todo

> Test

- [x] use `GetUser` API
- [x] user `UpdateUser` API
- [x] Error Handling - Duplicate Email
- [x] Error Handling - Duplicate username
- [x] Logout Implement.

## Trouble Shooting
> description

**Comment by kkminseok** [comment]
throw안해줘서 에러 못잡던거 해결함.
