### ISSUE TITLE
[FE] Article Detail Page

### ISSUE THREAD

**Issue by kkminseok** [kkminseok/real-world-springboot#43]
## Todo

> Implement

- [x] Article Detail Page Implement.
- [x] Mapping data
- [x] Functions
- [x] route profile
- [x] follow function
- [x] favorite function
- [x] write comment
- [x] comment status -> self = edit, remove
- [x] Article status -> sef = edit, remove
- [x] comment functions

## Todo

> Test

- [ ]

## Trouble Shooting
> description
